name: puppet_master
version: 0.0.1

environment:
  sdk: ">=1.23.0 <2.0.0"

dependencies:
  logging: 0.11.3+1
  w_transport: 3.2.1

dev_dependencies:
  test: 0.12.30+3
  dart_dev: 1.8.1
  analyzer: any
  coverage: any
  dart_style: any
  dartdoc: any
  mockito: 3.0.0-alpha

transformers:
  - test/pub_serve:
      $include: test/**_test.dart
